mv kodito.sfd kodito.fea
mv lekuta.sfd lekuta.fea
mv lozegw.sfd lozegw.fea
mv makina.sfd makina.fea
mv piswpi.sfd piswpi.fea
mv polwgo.sfd polwgo.fea
mv silwki.sfd silwki.fea
mv sulive.sfd sulive.fea
mv xavani.sfd xavani.fea
mv xesada.sfd xesada.fea
mv xidili.sfd xidili.fea
mv zosokw.sfd zosokw.fea
