#!/bin/zsh

echo "開くフォントのディレクトリ名を入力してください。"
ls -d */
read -p ">>> " fontname

inkscape ${fontname}/uni0021.svg
# !
inkscape ${fontname}/uni0022.svg
# "
inkscape ${fontname}/uni0023.svg
# #
inkscape ${fontname}/uni0024.svg
# $
inkscape ${fontname}/uni0025.svg
# %
inkscape ${fontname}/uni0026.svg
# &
inkscape ${fontname}/uni0027.svg
# '
inkscape ${fontname}/uni0028.svg
# (
inkscape ${fontname}/uni0029.svg
# )
inkscape ${fontname}/uni002a.svg
# *
inkscape ${fontname}/uni002b.svg
# +
inkscape ${fontname}/uni002c.svg
# ,
inkscape ${fontname}/uni002d.svg
# -
inkscape ${fontname}/uni002e.svg
# .
inkscape ${fontname}/uni002f.svg
# /
inkscape ${fontname}/uni0030.svg
# 0
inkscape ${fontname}/uni0031.svg
# 1
inkscape ${fontname}/uni0032.svg
# 2
inkscape ${fontname}/uni0033.svg
# 3
inkscape ${fontname}/uni0034.svg
# 4
inkscape ${fontname}/uni0035.svg
# 5
inkscape ${fontname}/uni0036.svg
# 6
inkscape ${fontname}/uni0037.svg
# 7
inkscape ${fontname}/uni0038.svg
# 8
inkscape ${fontname}/uni0039.svg
# 9
inkscape ${fontname}/uni003a.svg
# :
inkscape ${fontname}/uni003b.svg
# ;
inkscape ${fontname}/uni003c.svg
# <
inkscape ${fontname}/uni003d.svg
# =
inkscape ${fontname}/uni003e.svg
# >
inkscape ${fontname}/uni003f.svg
# ?
inkscape ${fontname}/uni0040.svg
# @
inkscape ${fontname}/uni0041.svg
# A
inkscape ${fontname}/uni0042.svg
# B
inkscape ${fontname}/uni0043.svg
# C
inkscape ${fontname}/uni0044.svg
# D
inkscape ${fontname}/uni0045.svg
# E
inkscape ${fontname}/uni0046.svg
# F
inkscape ${fontname}/uni0047.svg
# G
inkscape ${fontname}/uni0048.svg
# H
inkscape ${fontname}/uni0049.svg
# I
inkscape ${fontname}/uni004a.svg
# J
inkscape ${fontname}/uni004b.svg
# K
inkscape ${fontname}/uni004c.svg
# L
inkscape ${fontname}/uni004d.svg
# M
inkscape ${fontname}/uni004e.svg
# N
inkscape ${fontname}/uni004f.svg
# O
inkscape ${fontname}/uni0050.svg
# P
inkscape ${fontname}/uni0051.svg
# Q
inkscape ${fontname}/uni0052.svg
# R
inkscape ${fontname}/uni0053.svg
# S
inkscape ${fontname}/uni0054.svg
# T
inkscape ${fontname}/uni0055.svg
# U
inkscape ${fontname}/uni0056.svg
# V
inkscape ${fontname}/uni0057.svg
# W
inkscape ${fontname}/uni0058.svg
# X
inkscape ${fontname}/uni0059.svg
# Y
inkscape ${fontname}/uni005a.svg
# Z
inkscape ${fontname}/uni005b.svg
# [
inkscape ${fontname}/uni005c.svg
# \
inkscape ${fontname}/uni005d.svg
# ]
inkscape ${fontname}/uni005e.svg
# ^
inkscape ${fontname}/uni005f.svg
# _
inkscape ${fontname}/uni0060.svg
# `
inkscape ${fontname}/uni0061.svg
# a
inkscape ${fontname}/uni0062.svg
# b
inkscape ${fontname}/uni0063.svg
# c
inkscape ${fontname}/uni0064.svg
# d
inkscape ${fontname}/uni0065.svg
# e
inkscape ${fontname}/uni0066.svg
# f
inkscape ${fontname}/uni0067.svg
# g
inkscape ${fontname}/uni0068.svg
# h
inkscape ${fontname}/uni0069.svg
# i
inkscape ${fontname}/uni006a.svg
# j
inkscape ${fontname}/uni006b.svg
# k
inkscape ${fontname}/uni006c.svg
# l
inkscape ${fontname}/uni006d.svg
# m
inkscape ${fontname}/uni006e.svg
# n
inkscape ${fontname}/uni006f.svg
# o
inkscape ${fontname}/uni0070.svg
# p
inkscape ${fontname}/uni0071.svg
# q
inkscape ${fontname}/uni0072.svg
# r
inkscape ${fontname}/uni0073.svg
# s
inkscape ${fontname}/uni0074.svg
# t
inkscape ${fontname}/uni0075.svg
# u
inkscape ${fontname}/uni0076.svg
# v
inkscape ${fontname}/uni0077.svg
# w
inkscape ${fontname}/uni0078.svg
# x
inkscape ${fontname}/uni0079.svg
# y
inkscape ${fontname}/uni007a.svg
# z
inkscape ${fontname}/uni007b.svg
# {
inkscape ${fontname}/uni007c.svg
# |
inkscape ${fontname}/uni007d.svg
# }
inkscape ${fontname}/uni007e.svg
# ~