#!/bin/zsh

echo "開くフォントのディレクトリ名を入力してください。"
ls -d */
read fontname

touch ${fontname}/uni0021.svg
# !
touch ${fontname}/uni0022.svg
# "
touch ${fontname}/uni0023.svg
# #
touch ${fontname}/uni0024.svg
# $
touch ${fontname}/uni0025.svg
# %
touch ${fontname}/uni0026.svg
# &
touch ${fontname}/uni0027.svg
# '
touch ${fontname}/uni002a.svg
# *
touch ${fontname}/uni002b.svg
# +
touch ${fontname}/uni002c.svg
# ,
touch ${fontname}/uni002d.svg
# -
touch ${fontname}/uni002e.svg
# .
touch ${fontname}/uni002f.svg
# /
touch ${fontname}/uni0030.svg
# 0
touch ${fontname}/uni003a.svg
# :
touch ${fontname}/uni003b.svg
# ;
touch ${fontname}/uni003c.svg
# <
touch ${fontname}/uni003d.svg
# =
touch ${fontname}/uni003e.svg
# >
touch ${fontname}/uni003f.svg
# ?
touch ${fontname}/uni0040.svg
# @
touch ${fontname}/uni005c.svg
# \
touch ${fontname}/uni005e.svg
# ^
touch ${fontname}/uni005f.svg
# _
touch ${fontname}/uni0060.svg
# `
touch ${fontname}/uni007c.svg
# |
touch ${fontname}/uni007e.svg
# ~
